import datetime
from sunsynk.resource import Resource


class Flow(Resource):
    def __init__(self, data):
        self.custCode = data["custCode"]
        self.meterCode = data["meterCode"]
        self.pvPower = data["pvPower"]
        self.battPower = data["battPower"]
        self.gridOrMeterPower = data["gridOrMeterPower"]
        self.loadOrEpsPower = data["loadOrEpsPower"]
        self.genPower = data["genPower"]
        self.minPower = data["minPower"]
        self.soc = data["soc"]
        self.smartLoadPower = data["smartLoadPower"]
        self.upsLoadPower = data["upsLoadPower"]
        self.homeLoadPower = data["homeLoadPower"]
        self.pvTo = data["pvTo"]
        self.toLoad = data["toLoad"]
        self.toSmartLoad = data["toSmartLoad"]
        self.toUpsLoad = data["toUpsLoad"]
        self.toHomeLoad = data["toHomeLoad"]
        self.toGrid = data["toGrid"]
        self.toBat = data["toBat"]
        self.batTo = data["batTo"]
        self.gridTo = data["gridTo"]
        self.genTo = data["genTo"]
        self.minTo = data["minTo"]
        self.existsGen = data["existsGen"]
        self.existsMin = data["existsMin"]
        self.existsGrid = data["existsGrid"]
        self.genOn = data["genOn"]
        self.microOn = data["microOn"]
        self.existsMeter = data["existsMeter"]
        self.bmsCommFaultFlag = data["bmsCommFaultFlag"]
        self.existsThreeLoad = data["existsThreeLoad"]
        self.existsSmartLoad = data["existsSmartLoad"]
        self.pv = data["pv"]
        self.existThinkPower = data["existThinkPower"]
